[project]
name = 'TechCert'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.TechCert]
path = 'contracts/TechCert.clar'
clarity_version = 3
epoch = 3.1
[contracts.cert-portfolio]
path = 'contracts/cert-portfolio.clar'
clarity_version = 3
epoch = 3.1
[contracts.cert-mentorship]
path = 'contracts/cert-mentorship.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
